icon_mappings:
  full_1_col:
    "[6]":
      icon: "1col/six_columns.svg"
      name: "[6] of 12 columns Wide"
    "[8]":
      icon: "1col/eight_columns.svg"
      name: "[8] of 12 columns Wide"
    "[10]":
      icon: "1col/ten_columns.svg"
      name: "[10] of 12 columns Wide"
    "[12]":
      icon: "1col/twelve_columns.svg"
      name: "[12] of 12 columns Wide"
    "none":
      icon: "1col/stretch_wide.svg"
      name: "Stretch 100% wide"

  full_2_col:
    "[3|8]":
      icon: "2col/three_eight_columns.svg"
      name: "[3|8] of 12 columns Wide"
    "[3|9]":
      icon: "2col/three_nine_columns.svg"
      name: "[3|9] of 12 columns Wide"
    "[4|6]":
      icon: "2col/four_six_columns.svg"
      name: "[4|6] of 12 columns Wide"
    "[4|7]":
      icon: "2col/four_seven_columns.svg"
      name: "[4|7] of 12 columns Wide"
    "[4|8]":
      icon: "2col/four_eight_columns.svg"
      name: "[4|8] of 12 columns Wide"
    "[5|5]":
      icon: "2col/five_five_columns.svg"
      name: "[5|5] of 12 columns Wide"
    "[5|6]":
      icon: "2col/five_six_columns.svg"
      name: "[5|6] of 12 columns Wide"
    "[5|7]":
      icon: "2col/five_seven_columns.svg"
      name: "[5|7] of 12 columns Wide"
    "[6|4]":
      icon: "2col/six_four_columns.svg"
      name: "[6|4] of 12 columns Wide"
    "[6|5]":
      icon: "2col/six_five_columns.svg"
      name: "[6|5] of 12 columns Wide"
    "[6|6]":
      icon: "2col/six_six_columns.svg"
      name: "[6|6] of 12 columns Wide"
    "[7|4]":
      icon: "2col/seven_four_columns.svg"
      name: "[7|4] of 12 columns Wide"
    "[7|5]":
      icon: "2col/seven_five_columns.svg"
      name: "[7|5] of 12 columns Wide"
    "[8|3]":
      icon: "2col/eight_three_columns.svg"
      name: "[8|3] of 12 columns Wide"
    "[8|4]":
      icon: "2col/eight_four_columns.svg"
      name: "[8|4] of 12 columns Wide"
    "[9|3]":
      icon: "2col/nine_three_columns.svg"
      name: "[9|3] of 12 columns Wide"

  full_3_col:
    "[4|4|4]":
      icon: "3col/four_four_four_columns.svg"
      name: "[4|4|4] of 12 columns Wide"

  full_4_col:
    "[3|3|3|3]":
      icon: "4col/three_three_three_three_columns.svg"
      name: "[3|3|3|3] of 12 columns Wide"

  full_grid_2col:
    "[6]":
      icon: "grid2col/six_columns.svg"
      name: "[6] of 12 columns Wide (Grid)"
    "[8]":
      icon: "grid2col/eight_columns.svg"
      name: "[8] of 12 columns Wide (Grid)"
    "[10]":
      icon: "grid2col/ten_columns.svg"
      name: "[10] of 12 columns Wide (Grid)"
    "[12]":
      icon: "grid2col/twelve_columns.svg"
      name: "[12] of 12 columns Wide (Grid)"

  full_grid_3col:
    "[8]":
      icon: "grid3col/eight_columns.svg"
      name: "[8] of 12 columns Wide (Grid)"
    "[10]":
      icon: "grid3col/ten_columns.svg"
      name: "[10] of 12 columns Wide (Grid)"
    "[12]":
      icon: "grid3col/twelve_columns.svg"
      name: "[12] of 12 columns Wide (Grid)"

  full_grid_4col:
    "[10]":
      icon: "grid4col/ten_columns.svg"
      name: "[10] of 12 columns Wide (Grid)"
    "[12]":
      icon: "grid4col/twelve_columns.svg"
      name: "[12] of 12 columns Wide (Grid)"


