<?php

/**
 * @file
 * Site configuration.
 *
 * This module uses config_pages configuration to override 
 * a sites configuration to allow for personalization of a site.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\config_pages\Entity\ConfigPages;
use Drupal\node\NodeInterface;
use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_field_group_build_pre_render_alter().
 */
function custom_configuration_field_group_form_process_build_alter(&$element) {

  // Hide news field group if news content type is disabled.
  if (isset($element['group_news'])) {
    $element['group_news']['#states'] = [
      'invisible' => [
        ':input[name="field_site_disable_content[ed_news]"]' => ['checked' => TRUE]
      ]
    ];
  }

  // Hide Events field group if events content type is disabled.
  if (isset($element['group_events'])) {
    $element['group_events']['#states'] = [
      'invisible' => [
        ':input[name="field_site_disable_content[ed_event]"]' => ['checked' => TRUE]
      ]
    ];
  }
}
