name: Custom Configuration
description: 'Adds support for custom site configuration.'
package: 'Custom'
dependencies:
  - config_pages:config_pages

type: module
core: 8.x
version: '2.0.0'
core_version_requirement: ^8 || ^9
