name: Deploy Branch to Pantheon Multidev
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Use Node.js 16.19
      uses: actions/setup-node@v3
      with:
        node-version: '16.19'

    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: Install Terminus Build Tools
      run: terminus self:plugin:install terminus-build-tools-plugin

    - name: Update Ignore File.
      run: terminus build:gitignore:cut

    - name: Build Theme
      run:  |
        npm install
        npm run build
      working-directory: 'web/themes/utmusic'

    - name: Deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        git remote add pantheon $pantheon_repo
        git config --global user.email "fibot@fosterinteractive.com"
        git config --global user.name "FIBot"
        git add -A
        git commit -q -m 'Build theme.'
        git fetch --unshallow origin
        git push --force pantheon HEAD:refs/heads/$BASE_BRANCH
