name: Deploy Branch to Pantheon Multidev
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    #Install Terminus
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

    # Node Actions
    - uses: actions/checkout@v3
    - name: Use Node.js 16.
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    # Cache vendor folder
    - name: Cache vendor folder
      uses: actions/cache@v2
      env:
        cache-name: cache-vendor
      with:
        path: ./vendor
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}

    - run: npm install
      working-directory: 'web/themes/utmusic'
    - run: npm run build
      working-directory: 'web/themes/utmusic'
    
    
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        git remote add pantheon $pantheon_repo
        git add .
        git commit -q -m 'Build theme.'
        git push -u --force pantheon HEAD:refs/heads/$BASE_BRANCH
